---
title: "Teaching"
author: "Matias Andina"
output: html_document
---

I will add here ideas and projects from my teaching experiences. 

### Projects

NATSCI191 - Final Project.

I designed different experiments (using Google Forms and Matlab Psychtoolbox). Students participated as subjects, later analyzed the data, and presented their findings in class. Information about this project is available on [GitHub](https://github.com/matiasandina/NATSCI191). 

The learning objectives were:

* Familiarize students with graphical analysis of real data.
* Create a presentation-like experience for students going into Life Sciences. 

The results were gratifying. Students were curious about the tasks and the results. I guess there's a particular component given by the fact that all of them were subjects first. As a replication study, made during office hours and with a budged of 10 dollars for sodas and cups, I find it quite in line with previously reported findings (I felt so relieved). I will perform a more thorough analysis of the data, just for the fun.


### Courses

* NATSCI191 Animal Behavior, Fall 2017
